data:
  data_path: # Write your path of your data. Example: /home/dan/xag.csv
  path_to_copy: # Write your path where you want to copy your data. Example: /home/dan/output_data/
  filename_user: lookupuser
  filename_item: lookup_product

constant:
  penalty: 0.95
  day_in_second: 86400
  threshold: 0.01
